linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - misspell
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US

issues:
  exclude-dirs:
    - testdata
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
